### ISSUE TITLE
Need installations instructions for Mac OSX

### ISSUE THREAD

**Issue by r-b-e-e** [Chadsr/NordVPN-NetworkManager#101]
I tried installing using **Python PIP** in macOSX but it was tedious with lots of manual steps. I would suggest having Mac OSX installation using Homebrew package manager.

I had to upgrade python to 3.5 or above using `brew upgrade python`. Then ran `python3 -m pip install nordnm`

**Comment by Chadsr** [comment]
Hi,

This software requires Gnome's Network Manager to function. To the best of my knowledge, there is no possible way to use Network Manager on OSX (but please clarify if I am incorrect). So there will not be any planned support for OSX.

Feel free to re-open this issue if you can clarify in some way.
