### ISSUE TITLE
Benchmarking takes a while when there are a lot of free file descriptors

### ISSUE THREAD

**Issue by robbert-vdh** [Chadsr/NordVPN-NetworkManager#104]
Right now, nordnm tries to create a process pool the size of either the number of servers to benchmark or half the number of [available file descriptors](https://github.com/Chadsr/NordVPN-NetworkManager/blob/70c3f9be26511a927247cee7719be806f49c2d6a/nordnm/benchmarking.py#L78). I think this limit is set to 2048 by default on a lot of distros, but I had to increase it by a lot to be able to use [wine-esync](https://github.com/zfigura/wine/blob/esync/README.esync). This causes nordnm to spawn 4188 processes (one for each server) over the course of several minutes before starting the benchmark, even though benchmarking should only take a few seconds. Capping this number to, say, 512 processes would increase the speed of benchmarking by a lot.

**Comment by Chadsr** [comment]
As suggested, I have implemented a hard cap of 512 processes for now (f099ed34b65f29d8cb9ce4e3612f9175cda7ae56). This has been released in v0.6.0.

It's unclear if this benchmarking routine will be completely overhauled soon, so I will save any further changes for the re-design that is in progress.

Thanks again for the feedback.
I will close this issue for now.
