### ISSUE TITLE
Nordnm as a systemctl sevice

### ISSUE THREAD

**Issue by leon22heart** [Chadsr/NordVPN-NetworkManager#111]
Hello to all. I wanted to use nordnm to update automatically at startup the best servers and sync them at the network manager. The best way I found was to use a service file (because I  also intend to implement a timer later on). 
My service file has the form 

**nordm.service** 

`[Unit]
Description=My script

[Service]
ExecStart=/home/lolidas/Desktop/Scripts/Arch/NORDVPN.sh

[Install]
WantedBy=multi-user.target`

My **NORDVPN.sh** script has the form 

`#!/bin/bash
sudo nordnm sync
sudo nordnm -a NL normal udp`

Theoretically, everything should work perfectly. But in my case, the service fails to start. Further checking of the service log gives me the following message, indicating an EOF error in the python code.

`● nordm.service - My script
   Loaded: loaded (/etc/systemd/system/nordm.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2018-10-13 15:00:08 CEST; 11min ago
  Process: 6198 ExecStart=/home/lolidas/Desktop/Scripts/Arch/NORDVPN.sh (code=exited, status=1/FAILURE)
 Main PID: 6198 (code=exited, status=1/FAILURE)

Oct 13 15:00:08 lolidas NORDVPN.sh[6198]:   File "/usr/lib/python3.7/site-packages/nordnm/nordnm.py", line 314, in setup
Oct 13 15:00:08 lolidas NORDVPN.sh[6198]:     self.settings = SettingsHandler(paths.SETTINGS)
Oct 13 15:00:08 lolidas NORDVPN.sh[6198]:   File "/usr/lib/python3.7/site-packages/nordnm/settings.py", line 21, in __init__
Oct 13 15:00:08 lolidas NORDVPN.sh[6198]:     self.save_new_settings()
Oct 13 15:00:08 lolidas NORDVPN.sh[6198]:   File "/usr/lib/python3.7/site-packages/nordnm/settings.py", line 31, in save_new_s>
Oct 13 15:00:08 lolidas NORDVPN.sh[6198]:     whitelist = input("If you wish to synchronise only specific countries, enter the>
Oct 13 15:00:08 lolidas NORDVPN.sh[6198]: EOFError: EOF when reading a line
Oct 13 15:00:08 lolidas sudo[6220]: pam_unix(sudo:session): session closed for user root
Oct 13 15:00:08 lolidas systemd[1]: nordm.service: Main process exited, code=exited, status=1/FAILURE
Oct 13 15:00:08 lolidas systemd[1]: nordm.service: Failed with result 'exit-code'.
~
~
~
~
~
~
~
`

Thus I decided to report it as an issue since the error seems to concern the python code than any other part of the system. Using Archlinux 4.18.11 with python 3.7.

**Comment by Chadsr** [comment]
Hi,

Nice idea with the systemd service. I personally just tend to use the tool manually, but I may consider added a template .service file to the repo in the future.

Firstly a small note (but not the cause of the problem I don't think) - You can combine the commands into one run like so: `sudo nordnm sync -a nl normal udp` to save some running time.

Secondly, nordnm currently has a lot of user environment dependence, such as configuration files in the home folder. By default when running a systemd service, the script will be ran under the root user. From the output you have provided, I can see that nordnm was trying to prompt for settings, probably because it is running under root and couldn't find any.

If my hunch is correct, then under the `[Service]` section in your systemd unit file, adding a `User=YOUR_USERNAME` entry, followed by a restart of the service (`sudo systemctl restart nordnm`) should do the trick in allowing it to read configuration from your normal user.

Let me know if that solves the issue.

**Comment by leon22heart** [comment]
A very nice answer. Adding the `User=YOUR_USERNAME`  in the service file threw me the following error

`[root@lolidas:/home/lolidas]# systemctl status nordm                                                            (10-13 19:50)
● nordm.service - My script
   Loaded: loaded (/etc/systemd/system/nordm.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2018-10-13 19:50:30 CEST; 3s ago
  Process: 18015 ExecStart=/home/lolidas/Desktop/Scripts/Arch/NORDVPN.sh (code=exited, status=1/FAILURE)
 Main PID: 18015 (code=exited, status=1/FAILURE)

Oct 13 19:50:30 lolidas systemd[1]: Started My script.
Oct 13 19:50:30 lolidas NORDVPN.sh[18015]: sudo: no tty present and no askpass program specified
Oct 13 19:50:30 lolidas sudo[18016]: pam_unix(sudo:auth): conversation failed
Oct 13 19:50:30 lolidas sudo[18016]: pam_unix(sudo:auth): auth could not identify password for [lolidas]
Oct 13 19:50:30 lolidas systemd[1]: nordm.service: Main process exited, code=exited, status=1/FAILURE
Oct 13 19:50:30 lolidas systemd[1]: nordm.service: Failed with result 'exit-code'.
`

Reading through posts and specifically from here [https://unix.stackexchange.com/questions/18830/how-to-run-a-specific-program-as-root-without-a-password-prompt](url) I found that I needed to edit the `/etc/sudoers` file and add the option `lolidas ALL = (ALL) NOPASSWD: /bin/nordnm` where lolidas is my username. Thus now everything works perfectly fine. I also include my `.timer` file in case anyone is interested in refreshing the service. I have set mine to re-execute every 59 minutes.

**nordm.timer**
`[Unit]
Description=Run nordm.service every 59 minutes
Requires=nordm.service

[Timer]
OnBootSec=3min
Persistent=true
Unit=nordm.service
OnCalendar=*:0/59

[Install]
WantedBy=multi-user.target`
