### ISSUE TITLE
wiki contributions

### ISSUE THREAD

**Issue by atomGit** [Chadsr/NordVPN-NetworkManager#116]
i'd like to add content to the wiki if desired, but would like to know how best to do that (pull requests? open an issue? etc.)

**Comment by Chadsr** [comment]
Wow, I'm sorry for missing this. Somehow I overlooked it.

Adding some content to the wiki would be great if you are still wanting to. I think making pull requests would be the easiest, so we can review and make changes through git.

**Comment by atomGit** [comment]
i actually don't use the network manager anymore unfortunately - i have my VPN connection set up on my router - sorry 'bout that :)
