### ISSUE TITLE
The 'nordnm==0.6.1' distribution was not found....

### ISSUE THREAD

**Issue by Prisoner709** [Chadsr/NordVPN-NetworkManager#117]
Hi, this is my problem in Fedora 29 with phyton 3.7. 

bash-4.4$ sudo nordnm list --categories --countries
Traceback (most recent call last):
  File "/usr/bin/nordnm", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nordnm==0.6.1' distribution was not found and is required by the application
bash-4.4$
Thanks for the answer.

**Comment by sorin-davidoi** [comment]
I think I'm encountering the same issue, a workaround is to install via `pip` as root (which is not recommended):

```bash
sudo -H pip3 install nordnm
sudo nordnm update --credentials
sudo nordnm sync --update-configs --kill-switch --auto-connect de normal tcp
sudo restorecon -r /root/.cert # Restore default SELinux security contexts (otherwise it fails to connect)
```

**Comment by ShinJii89** [comment]
> I think I'm encountering the same issue, a workaround is to install via `pip` as root (which is not recommended):
> 
> ```shell
> sudo -H pip3 install nordnm
> sudo nordnm update --credentials
> sudo nordnm sync --update-configs --kill-switch --auto-connect de normal tcp
> sudo restorecon -r /root/.cert # Restore default SELinux security contexts (otherwise it fails to connect)
> ```

It worked for me - thanks!

**Comment by Chadsr** [comment]
Sorry for the long silence. Development on this halted for a while as I don't use NordVPN at the moment.

I just made a release (0.7.0) which will prevent this from happening. It's only a temporary fix until the next major python version is released, since I am currently using absolute paths to python library directories when building the rpm package... Really not ideal.

I will close this issue for now, in favour of #120. If you encounter this again, feel free to re-open of course.

**Comment by Prisoner709** [comment]
> Sorry for the long silence. Development on this halted for a while as I don't use NordVPN at the moment.
> 
> I just made a release (0.7.0) which will prevent this from happening. It's only a temporary fix until the next major python version is released, since I am currently using absolute paths to python library directories when building the rpm package... Really not ideal.
> 
> I will close this issue for now, in favour of #120. If you encounter this again, feel free to re-open of course.

Don't worry about the silence. Thank you all for the answers.
