### ISSUE TITLE
Can't connect after latest update

### ISSUE THREAD

**Issue by leedaz** [Chadsr/NordVPN-NetworkManager#121]
Getting this error whilst using this command..  sudo nordnm sync -ka gb normal udp

[ERROR] [nordnm.nordnm.enable_auto_connect:494] Auto-connect not activated: No active server found matching [gb, normal, udp]

I have been using 'sudo nordnm s -uka gb normal udp' successfully for over a year, but now it wont work. Have uninstalled/deleted .nordnm folder and restarted from scratch. Can someone tell me what I'm doing wrong. Thanks.

**Comment by kotasher** [comment]
Can confirm this on latest arch. The problem is possibly because of new sudo mechanism. Nordnm cannot refresh network manager entries. Also it does not fill credentials, one has to explicitly fill them in order to connect.

**Comment by Chadsr** [comment]
Apologies, I released the last update without thorough testing as I dont currently use NordVPN/this tool. 

I will get my hands on a login and figure  out how I screwed up. (Or if you already see, PRs are most welcome)

I will rollback the aur package until it's fixed.

**Comment by whoisroot** [comment]
I think the problem is with privileges management, because it fails updating the connections on `nmcli`. And because it did not update the connections to include the synced ones, it fails to connect.

**Comment by ShinJii89** [comment]
Same problem in Fedora 30....

> [ERROR] [nordnm.networkmanager.enable_connection:345]  (process:4594): Gtk-WARNING **: 11:09:54.687: This process is currently running setuid or setgid. This is not a supported use of GTK+. You must create a helper program instead. For further details, see:      http://www.gtk.org/setuid.html  Refusing to initialize GTK+. Ostrzeżenie: w „passwd-file” nie podano hasła dla „vpn.secrets.password”, a program nmcli nie może zapytać bez opcji „--ask”.


How to downgrade to 0.6.x?
