### ISSUE TITLE
DNS leak?

### ISSUE THREAD

**Issue by peteruithoven** [Chadsr/NordVPN-NetworkManager#42]
Looking at http://dnsleaktest.com/ and https://www.expressvpn.com/dns-leak-test it seemed like I still had a dns leak after configuring my vpn settings using nordnm.

After I followed the following article and added the following lines to the active .ovpn file and restarted wifi the leak seems gone.
```
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```
http://www.ubuntubuzz.com/2015/09/how-to-fix-openvpn-dns-leak-in-linux.html

I'm still quite a noob in regards to vpn, but I don't get why this isn't included by default in the ovpn files of NordVPN, maybe nordnm should add them? Is there a easier / better way to fix this?

**Comment by peteruithoven** [comment]
Found more resources: 
https://wiki.archlinux.org/index.php/OpenVPN#DNS
https://github.com/jonathanio/update-systemd-resolved
https://roy.marples.name/projects/openresolv

https://protonvpn.com/support/linux-vpn-setup/
Mentions: 
> Attention: At this point, there is a known issue with DNS Leaks on distributions up to Ubuntu 16.04LTS (and its dependencies and parents). If you find that you too are affected by DNS leaks, we recommend you to use Option B below.

A interesting comment:
>  4 / for all your connections, but not the VPN profile: go to the IPv4 tab: set it to IP adress only (DHCP) and let the DNS server adress blank, in order to have no DNS resolver (think about saving your preexistent ones in .txt if there are)
5/ for all your connections and the VPN profile: set IPv6 tab to ignore (so you avoid ipv6 hazardous leaks)

Reading through: https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1211110
Lot's of me too'2 and conflicting answers, Launchpad (without a like or up/down voting system is making this extra painful). Comments that seem interesting:
- https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1211110/comments/11
- https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1211110/comments/58
- https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1211110/comments/70
- https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1211110/comments/78
- https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1211110/comments/92

**Comment by peteruithoven** [comment]
I've had issues with dnsleaktest.com (it doesn't always start the tests). https://ipleak.net/ seems to work better. Currently, on ipleak.net, the ip that shows up seems to be the ip of the NordVPN server I'm connected to. Even after removing the above mentioned lines from the ovpn file. I'm going to keep testing it now and than, because I'm sure the other tests sites showed issues.

**Comment by peteruithoven** [comment]
I'm closing this issue, I'll reopen when I notice leaks again.

**Comment by peteruithoven** [comment]
Article on the subject: https://www.bestvpn.com/a-complete-guide-to-ip-leaks/#ipv6leaks

Relevant part:
> When using a VPN, your Operating System (OS) can sometimes get confused, sending IPv4 requests through to the DNS server specified in its default settings (usually run by your ISP), instead of through the VPN tunnel (as it’s supposed to.) This can occur with any OS, but Windows is notably guilty in this respect.
> 
> **Fixes**
> 
> 1. Use a VPN client with built-in “DNS leak protection”. This is basically just a firewall that ensures no internet traffic can leave your computer unless it goes through the VPN. Many good providers offer this feature in their custom VPN clients (sometimes called something else), but it is not available in the generic open source OpenVPN client.

@Chadsr could you mayle clarify in the readme whether you've taken precautions. You for example already mention you block IPv6.
I see you set the dns nameservers and you enable "ignore-auto-dns". But I couldn't find any firewall/iptables code.

**Comment by Chadsr** [comment]
I have a fix pushed in #52 regarding this issue. The fix, along with other features will be in the next version (v0.2.0) for you to test out.

/etc/resolv.conf is now explicitly modified and "frozen" (made immutable) so that nameservers can not be modified, when an VPN is active. This should hopefully prevent any future possibilities of DNS request leaks.

**Comment by Chadsr** [comment]
Once again, it seems Ubuntu wants to be special and do things in a strange/annoying way. The fix I mentioned is partially broken on Ubuntu systems. It still changes the nameservers correctly, but it doesn't lock them down, or revert back to default nameservers when the VPN drops.

Sorry if you come across this annoyance. If you nameservers get stuck with the NordVPN servers when your VPN is disconnected, a reboot should fix it.

In the meantime, I'm working on a patch for Ubuntu systems.

**Comment by Chadsr** [comment]
Aaand I have pushed *hopefully* the last fix needed regarding DNS leaks. v0.2.1 should work perfectly in all distros now.

**Comment by Chadsr** [comment]
I will close this again, until any further problems are found (but hopefully that was it).

**Comment by BobbyBabes** [comment]
Please do not add iptables. Or implement ip-tables with an opt-out.
My PC is iptables free. No firewall. No (virus) scanners. I like to keep it that way.
