### ISSUE TITLE
Random order "Enable category" questions?

### ISSUE THREAD

**Issue by peteruithoven** [Chadsr/NordVPN-NetworkManager#60]
Minor issue, but the category questions seem to be asked in a random order, for example when setting new settings twice: 
```
Enable category 'P2P'? (y/n): y
Enable category 'Double VPN'? (y/n): n
Enable category 'Onion over VPN'? (y/n): n
Enable category 'Dedicated IP servers'? (y/n): n
Enable category 'Standard VPN servers'? (y/n): y
Enable category 'Anti DDoS'? (y/n): n
```
```
Enable category 'Standard VPN servers'? (y/n): y
Enable category 'P2P'? (y/n): y
Enable category 'Onion over VPN'? (y/n): n
Enable category 'Anti DDoS'? (y/n): n
Enable category 'Dedicated IP servers'? (y/n): n
Enable category 'Double VPN'? (y/n): n
```

It's almost as if the `keys()` method returns items in a random order, see: https://github.com/Chadsr/NordVPN-NetworkManager/blob/master/nordnm/settings.py#L43
Maybe a alphabetical sorting could be added?

**Comment by Chadsr** [comment]
Great, thanks for the fix. I too had noticed this, but it slipped my mind to make a fix.

Closing the issue.
