### ISSUE TITLE
Incorrectly installed on Fedora 27

### ISSUE THREAD

**Issue by bocekm** [Chadsr/NordVPN-NetworkManager#78]
I'm getting the following traceback after installing the tool through `https://bintray.com/chadsr/nordnm-rpm/rpm` repo:
```
nordnm
Traceback (most recent call last):
  File "/usr/bin/nordnm", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3125, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nordnm==0.4.0' distribution was not found and is required by the application
```
The problem seems to be that the tool has been installed to `/usr/lib/python3/site-packages/` and it's the only python module in this folder. I have all the other python modules in `/usr/lib/python3.6/site-packages/`. After moving the module manually there, the tool works.

**Comment by Chadsr** [comment]
Thanks for pointing this out.

This tool was my first try at automated cross-distribution packaging and there's a few issues with it right now. I will investigate a better approach / fix for where the tool is being installed to and reference this issue when a fix is made.

Glad you found a temporary fix by simply moving it for now!

**Comment by bocekm** [comment]
Yeah, the thing is the RPM already contains exact paths to which the tool's files should be installed. And the python packages are to be installed to a path `/usr/lib/python3.6/site-packages/` which needs to contain the python version including the minor version. What for example each Fedora version has its own repo and the python module packages contain the path based on what Python version is shipped with the Fedora. Unfortunately there can't be a single rpm which would work after installation with whatever minor version of Python 3. Or at least I'm not aware of such solution.

**Comment by bocekm** [comment]
But take a look at pyp2rpm tool which prepares a rpm spec file for you.

**Comment by bocekm** [comment]
I'm on Fedora 28 and I was able to install the v0.5.4 without a problem. It is installed in `/usr/lib/python3.6/`. So the quick fix works so far.

**Comment by Chadsr** [comment]
Good to hear. Packages from now on are tested with the latest version of fedora and ubuntu, so hopefully these little issues can be avoided in the future.

I shall close this issue for now. Thanks for the feedback!
