### ISSUE TITLE
Can't remove Kill Switch

### ISSUE THREAD

**Issue by nerdyman** [Chadsr/NordVPN-NetworkManager#97]
Hi,

I was trying out nordnm from the [AUR](<https://aur.archlinux.org/packages/nordnm/>) but removed it before disabling the kill swtich. Now everytime I try to connect the normal adapter (`en01`) it immediately disconnects and I have to kill `dhcpcd` and reconnect again manually. This now means I can't use `nm-applet` to select and configure networks because as soon as I edit `en01` it disconnects again.

I've reinstalled and tried the following:

```BASH
sudo nordnm r -k
[INFO] [nordnm.nordnm]: Nothing to remove.
```

```BASH
sudo nordnm r --all
[ERROR] [nordnm.utils]: Could not check PyPi for latest version.
     _   _               _ _   _ ___  ___
    | \ | |             | | \ | ||  \/  |
    |  \| | ___  _ __ __| |  \| || .  . |
    | . ` |/ _ \| '__/ _` | . ` || |\/| |
    | |\  | (_) | | | (_| | |\  || |  | |
    \_| \_/\___/|_|  \__,_\_| \_/\_|  |_/   v0.5.4

[INFO] [nordnm.nordnm]: No active connections to remove.
[INFO] [nordnm.nordnm]: Data directory does not exist. Nothing to remove.
[INFO] [nordnm.nordnm]: Data directory '/home/me/.nordnm/' removed successfully!
```

But it still disconnects immediately. Is it possible there's a lingering config setting somewhere that is keeping the kill switch alive?

Thanks!

**Comment by Chadsr** [comment]
Sorry you ran into this annoyance. Adding a more graceful uninstall procedure is pretty high on my todo list.

> I've reinstalled and tried the following:
sudo nordnm r -k
[INFO] [nordnm.nordnm]: Nothing to remove.

Hm, that's odd. I will look into why a reinstall stopped it from finding scripts to remove. That is very much unintended behaviour.

But anyway, to manually remove any scripts/settings nordnm may have left over on your system, you can run:
`sudo rm /etc/NetworkManager/dispatcher.d/nordnm*`
and
`rm -rf ~/.nordnm`

The first command should confirm to delete a `nordnm_killswitch_$USERNAME` file, which is the culprit for the killswitch disconnects.

That should be it!

**Comment by nerdyman** [comment]
That's fixed it thanks!

I should also mention I initially removed the tool because I didn't realise I'd enabled the kill switch and thought it broke something, I'm back to using it (properly) now so thanks again.
