### ISSUE TITLE
Yaourt misleading message

### ISSUE THREAD

**Issue by philippera** [Chadsr/NordVPN-NetworkManager#98]
First of all thanks for making nordnm.
When installed it with yaourt (I use manjaro) some comments from the ArchLinux nordnm page are printed out. One of the comments was a copy/paste from a python error reported by maiaftv. So when I installed nordnm with yaourt it looked like there was a python error. No big deal but it is misleading and some people might giving up on installing it so I thought I report it.
Cheers,

**Comment by philippera** [comment]
Wow the program works seemlessly on manjaro-i3. Great tool! Many thank yous.

**Comment by Chadsr** [comment]
Hi and thanks for the feedback.

Unfortunately, there's not a lot I can do about the contents of those comments and the fact that they show up when installing from the AUR.
I think that design decision is mostly so users can immediately see what the latest comments are before making an install. Just in case there's some issue they face which is already being discussed, etc. 
So I can see that it may cause confusion if there are stack-traces being printed out, but it's actually designed to lessen the confusion if users face problems whilst doing an install! :)

Glad you're finding nordnm useful!

**Comment by Chadsr** [comment]
I will close this, as I don't think there is anything I can do to prevent confusion, sorry!
