### ISSUE TITLE
Closing double quote

### ISSUE THREAD

**Issue by moonk5** [Chadsr/NordVPN-NetworkManager#99]
Found there is a missing closing double quote in _nordnm/networkmanger.py_ (line 204)
which caused a syntax error.
Here is the link from [last commit](https://github.com/Chadsr/NordVPN-NetworkManager/commit/2ee609667205cbf9de7ecf3cb70eda437b5befac).
Thanks.

**Comment by Chadsr** [comment]
Whoopsie, thanks for the catch. My linter was a little disfunctional a while ago and I guess this slipped through as a result.

I have pushed a fix (e816292), but since it isn't preventing the functionality, it might wait until a larger release before it gets deployed.

**Comment by utf8please** [comment]
This should be already included in the tag 0.5.5. Shall we close this? @Chadsr
